"""
Unsloth QLoRA Fine-Tuning — Veles Finance v6
Trains on fin_dataset.jsonl generated by fincot_generator.py.
Optimized for RTX 3060 12GB (~9-10 GB VRAM peak).

Usage:
    pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    pip install trl transformers datasets accelerate bitsandbytes
    python unsloth_qlora.py
    python unsloth_qlora.py --base drushka/Veles-Finance-7B-v5  # resume from v5
    python unsloth_qlora.py --epochs 3 --rank 32                # custom params
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────
DATASET_PATH   = str(Path(__file__).parent / "data" / "fin_dataset.jsonl")
OUTPUT_ADAPTER = str(Path(__file__).parent / "models" / "veles-finance-7b-v6-lora")
OUTPUT_MERGED  = str(Path(__file__).parent / "models" / "veles-finance-7b-v6-merged")

DEFAULT_BASE   = "unsloth/Qwen2.5-7B-Instruct-bnb-4bit"
MAX_SEQ_LEN    = 4096
LOAD_IN_4BIT   = True


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--base",   default=DEFAULT_BASE, help="Base model (HF path or local)")
    p.add_argument("--epochs", type=int,   default=2)
    p.add_argument("--rank",   type=int,   default=16,    help="LoRA rank (16 or 32)")
    p.add_argument("--lr",     type=float, default=2e-4)
    p.add_argument("--batch",  type=int,   default=2,     help="Per-device batch size")
    p.add_argument("--grad-accum", type=int, default=4,   help="Gradient accumulation steps")
    p.add_argument("--merge",  action="store_true",       help="Merge & save full model after training")
    p.add_argument("--push",   action="store_true",       help="Push merged model to HuggingFace Hub")
    p.add_argument("--hf-repo", default="Drushka/Veles-Finance-7B-v6")
    return p.parse_args()


def main():
    args = parse_args()

    # Validate dataset exists
    if not Path(DATASET_PATH).exists():
        sys.exit(f"Dataset not found: {DATASET_PATH}\n"
                 "Run: python fincot_generator.py")

    import torch
    from unsloth import FastLanguageModel
    from unsloth.chat_templates import get_chat_template
    from datasets import load_dataset
    from trl import SFTTrainer
    from transformers import TrainingArguments

    print(f"\n{'='*60}")
    print(f"Veles Finance v6 — QLoRA Fine-Tuning")
    print(f"Base model:  {args.base}")
    print(f"Dataset:     {DATASET_PATH}")
    print(f"Rank:        {args.rank}  |  Epochs: {args.epochs}  |  LR: {args.lr}")
    print(f"CUDA:        {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'NOT AVAILABLE'}")
    print(f"{'='*60}\n")

    # ── 1. Load model ─────────────────────────────────────────────────────
    print("Loading base model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=args.base,
        max_seq_length=MAX_SEQ_LEN,
        dtype=None,                      # auto: fp16 for RTX 3060
        load_in_4bit=LOAD_IN_4BIT,
    )

    # ── 2. LoRA adapters ──────────────────────────────────────────────────
    print("Applying LoRA adapters...")
    model = FastLanguageModel.get_peft_model(
        model,
        r=args.rank,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=args.rank * 2,        # 2x rank is standard
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",  # saves ~30% VRAM
        random_state=3407,
        use_rslora=False,
    )
    print(f"Trainable params: {sum(p.numel() for p in model.parameters() if p.requires_grad):,}")

    # ── 3. Dataset ────────────────────────────────────────────────────────
    print("Formatting dataset...")

    # Use chat template matching the base model
    template = "qwen-2.5" if "qwen" in args.base.lower() else "chatml"
    tokenizer = get_chat_template(
        tokenizer,
        chat_template=template,
        mapping={"role": "from", "content": "value",
                 "user": "user", "assistant": "assistant"},
    )

    def format_sample(examples):
        texts = [
            tokenizer.apply_chat_template(
                convo, tokenize=False, add_generation_prompt=False
            )
            for convo in examples["conversations"]
        ]
        return {"text": texts}

    dataset = load_dataset("json", data_files=DATASET_PATH, split="train")
    # Filter out any samples where model generation failed
    dataset = dataset.filter(lambda x: "__PLACEHOLDER__" not in x["conversations"][2]["value"]
                             and "<error>" not in x["conversations"][2]["value"])
    dataset = dataset.map(format_sample, batched=True)
    print(f"Training samples: {len(dataset)}")

    # ── 4. Trainer ────────────────────────────────────────────────────────
    Path(OUTPUT_ADAPTER).parent.mkdir(parents=True, exist_ok=True)

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LEN,
        dataset_num_proc=2,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=args.batch,
            gradient_accumulation_steps=args.grad_accum,
            warmup_steps=max(10, len(dataset) // 50),
            num_train_epochs=args.epochs,
            learning_rate=args.lr,
            fp16=not torch.cuda.is_bf16_supported(),
            bf16=torch.cuda.is_bf16_supported(),
            logging_steps=10,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="cosine",
            seed=3407,
            output_dir=OUTPUT_ADAPTER + "_checkpoints",
            save_strategy="epoch",
            report_to="none",
        ),
    )

    # ── 5. Train ──────────────────────────────────────────────────────────
    print("\nStarting training...")
    stats = trainer.train()
    print(f"\nTraining complete!")
    print(f"  Loss:    {stats.training_loss:.4f}")
    print(f"  Runtime: {stats.metrics['train_runtime']:.0f}s "
          f"({stats.metrics['train_runtime']/60:.1f} min)")

    # ── 6. Save adapter ───────────────────────────────────────────────────
    print(f"\nSaving LoRA adapter → {OUTPUT_ADAPTER}")
    model.save_pretrained(OUTPUT_ADAPTER)
    tokenizer.save_pretrained(OUTPUT_ADAPTER)

    # ── 7. Optional: merge + push ─────────────────────────────────────────
    if args.merge or args.push:
        print(f"Merging adapter into full model → {OUTPUT_MERGED}")
        model.save_pretrained_merged(
            OUTPUT_MERGED, tokenizer,
            save_method="merged_16bit",
        )

    if args.push:
        hf_token = os.getenv("HF_TOKEN")
        if not hf_token:
            print("Set HF_TOKEN env var to push to HuggingFace Hub")
        else:
            print(f"Pushing to HuggingFace Hub → {args.hf_repo}")
            model.push_to_hub_merged(
                args.hf_repo, tokenizer,
                save_method="merged_16bit",
                token=hf_token,
            )
            print(f"Published: https://huggingface.co/{args.hf_repo}")

    print("\nDone! Next steps:")
    print(f"  1. Test adapter:  ollama create veles-v6 -f Modelfile")
    print(f"  2. Run benchmark: python benchmark.py")
    print(f"  3. Push to HF:    python unsloth_qlora.py --push")


if __name__ == "__main__":
    main()
